.nh
.TH "GH-ATTESTATION" "1" "May 2024" "GitHub CLI 2.49.2" "GitHub CLI manual"

.SH NAME
.PP
gh-attestation - Work with artifact attestations


.SH SYNOPSIS
.PP
\fBgh attestation [subcommand] [flags]\fR


.SH DESCRIPTION
.SS NOTE: This feature is currently in beta, and subject to change.
.PP
Download and verify artifact attestations.


.SH AVAILABLE COMMANDS
.TP
\fBgh-attestation-download(1)\fR
Download an artifact's attestations for offline use

.TP
\fBgh-attestation-verify(1)\fR
Verify an artifact's integrity using attestations


.SH SEE ALSO
.PP
\fBgh(1)\fR
